name: Jason Richardson
favicon: null
layout_spectrum: 0.5201281120534986
typography_spectrum: 0.4626296693459153
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5265900646336377
  lightness: 0.34013842046260834
  saturation: 0.4093178112525493
  rhythmicContrast: 0.5446846992708743
purpose: []
