name: Jason Richardson
favicon: null
layout_spectrum: 0.49967
typography_spectrum: 0.78318
title: Jason Richardson - Game Design
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020202'
    - '#1f2d1e'
    - '#966b64'
    - '#cfc2b9'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.4093178112525493
  rhythmicContrast: 0.5
purpose: []
